### ISSUE TITLE
Weird Distortions when outside Voxel Bounds

### ISSUE THREAD

**Issue by michaelsakharov** [pipliz/cpuvox#3]
![image](https://user-images.githubusercontent.com/8621606/83299261-2ffa7480-a239-11ea-9b56-1afc0431e7a1.png)
Weird Distortions appears to only happen when outside the "World".
Happens both In Editor and In Build, using unity 2019.3.0f5.

**Comment by michaelsakharov** [comment]
Seems to be connected to LOD, LOD Power changes it. Lod power of 0.1 and it seems to stop happening.

**Comment by pipliz** [comment]
I think this is a regression from this commit (24th may)
https://github.com/pipliz/cpuvox/commit/79971ab59dcd1def3e0f2f599138cd947e8b713a
that's fixed in this commit (29th may)
https://github.com/pipliz/cpuvox/commit/b816926d8ae3dd35b907857a1a7e96f1ed977c7c

if the ray would change LOD in the "pre stepping" job, the main job wouldn't be setting up the ray plane parameters properly

check if it still occurs in the master branch

**Comment by michaelsakharov** [comment]
Seems to be fixed!
