### ISSUE TITLE
Lines appears in Build

### ISSUE THREAD

**Issue by michaelsakharov** [pipliz/cpuvox#4]
![image](https://user-images.githubusercontent.com/8621606/83299532-b3b46100-a239-11ea-9018-ec354fe217b4.png)

Weird Lines appear to only happen in Builds works fine in editor, Looking around changes it, if i look in just the right direction/angle they dissapear.

**Comment by pipliz** [comment]
It's plausible this was fixed in
https://github.com/pipliz/cpuvox/commit/b72d6fe74e85f1990322e6c6a0511820d1fc1347
this changed the frustum values used from -1 .. 1 to 0 .. screen, but critically adds a small offset to the frustum to prevent it from becoming exactly 0, which was causing a divide by zero in the frustum clipping code

**Comment by michaelsakharov** [comment]
Seems fixed!
